
```{r setup, cache = F, echo = F, message = F,include=F,results='hide', warning = F, tidy = F}
# make this an external chunk that can be included in any file
opts_chunk$set(message = T, error = T, warning = T, comment = NA, fig.align = 'center', dev="CairoPNG",
  		   dpi = 72, tidy = F, cache = F,echo=T,include=F, cache.path = '.cache/',
			   fig.path = 'fig/',fig.height=5,fig.width=10, par(pch=19))

options(xtable.type = 'html', width=68,digits=1, show.signif.stars=FALSE)
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
library(knitr); library(knitcitations)
bib <- read.bibtex("rrmda.bib")
cite_options(tooltip = FALSE, linked = TRUE,
    numerical = TRUE, bibtex_data = FALSE)
#
#Reading in your own bib file:
#bib <- read.bibtex(file.path(getwd(), "Presentation", basename(getOption("bib.loc"))))
#cite in text using `r citet(bib[1])`
```

```{r mainLibr}

library(Hmisc)
library(reshape)
library(survival)
require(openintro)
library(car)
library(psych)
library(ggplot2)
library(lattice)
require(mosaic)
require(xtable)
library(RColorBrewer)
trellis.par.set(theme=col.mosaic())  # get a better color scheme for lattice
source("~/Dropbox/R_Scripts/glob_r_scr/print_pval.R")
source("~/Dropbox/R_Scripts/glob_r_scr/median_range.R")

```


```{r loadData}
source("code/data_prep.R")
```

```{r Versions}
sessionInfo()
```

This is a Reproducable researche Rmarkdow example.
========================================================



**Abstract**


__Objective__


__Methods__


__Results__


__Conlutions__

Introduction
------------
This is how to cite in knitr with knitrcitations `r citep(bib["bentall_technique_1968"])`. 


Material and methods
------------
This is the first table __Table__ 1.







```{r plot3, fig.height=3, fig.width=9,fig.keep='high',include=TRUE, fig.cap="A histogram and density estimates for three outcomes."}
par(mfrow=c(1,3))
hist(outcome[,11],xlab="30-day Death Rate",main=substitute(bar(X)==k,list(k=mean(outcome[,11],na.rm=TRUE))),xlim=c(0,20),prob=TRUE)
lines(density(outcome[,11],na.rm=TRUE),col="red")             # add a density estimate with defaults
abline(v=median(outcome[,11],na.rm=TRUE),col="blue")
abline(h=0)
hist(outcome[,17],xlab="30-day Death Rate",main=substitute(bar(X)==k,list(k=mean(outcome[,17],na.rm=TRUE))),xlim=c(0,20),prob=TRUE)
lines(density(outcome[,17],na.rm=TRUE),col="red") 
abline(v=median(outcome[,17],na.rm=TRUE),col="blue")
abline(h=0)
hist(outcome[,23],xlab="30-day Death Rate",main=substitute(bar(X)==k,list(k=mean(outcome[,23],na.rm=TRUE))),xlim=c(0,20),prob=TRUE)
lines(density(outcome[,23],na.rm=TRUE),col="red") 
abline(v=median(outcome[,23],na.rm=TRUE),col="blue")
abline(h=0)
```



